### ISSUE TITLE
Fix: QMetaType.Type syntax broken on QGIS 4.0.1 (Qt6)

### ISSUE THREAD

**Issue by FloraFlorestal** [LEOXINGU/lftools#29]
**Bug: QMetaType.QString AttributeError on QGIS 4.0.1 (Qt6)**

**QGIS version:** 4.0.1-Norrköping
**Qt version:** 6.8.1
**Python version:** 3.12.13
**LFTools version:** 2.10.3
**OS:** Windows

---

**Description**

After updating from QGIS 4.0.0 to 4.0.1, all LFTools algorithms that define QgsField fail with the following error:

AttributeError: type object 'QMetaType' has no attribute 'QString'

**Root cause**

QGIS 4.0.1 enforces the Qt6 enum syntax for QMetaType. The attribute access `QMetaType.QString` (and other types such as `Int`, `Double`, `Bool`, etc.) no longer works. The correct syntax is `QMetaType.Type.QString`.

This was a breaking change introduced between QGIS 4.0.0 and 4.0.1.

**Fix**

All occurrences of `QMetaType.<Type>` must be replaced with `QMetaType.Type.<Type>` across the plugin source files.

A regex substitution resolves the issue:

- Pattern: `QMetaType\.(?!Type\.)(<typename>)`
- Replacement: `QMetaType.Type.\1`

Applying this replacement across all `.py` files in the plugin fixed the issue completely (41 files, 263 substitutions in our environment).

**Steps to reproduce**

1. Install QGIS 4.0.1
2. Install LFTools
3. Run any LFTools algorithm that creates QgsField (e.g. "Geotagged Photos")
4. Observe the AttributeError in the log

**Comment by LEOXINGU** [comment]
Thanks for reporting this issue and for the detailed investigation.

This bug has already been fixed in LFTools version 2.11.0, including compatibility adjustments for the Qt6/QGIS 4.0 changes related to QMetaType.Type.

Please update LFTools to version 2.11.0 from the official QGIS Plugin Repository.

If the problem still persists after updating, please let me know and I will investigate further.

Thank you for the report and contribution.
